import { SocialPlatformConfig, SocialPlatformId } from '../types/social_osint';

export const SOCIAL_PLATFORMS: Record<SocialPlatformId, SocialPlatformConfig> = {
  github: {
    id: 'github',
    name: 'GitHub',
    category: 'Developer & Code',
    baseUrl: 'https://github.com/',
    iconName: 'Github',
    color: '#2ea44f',
    bgLight: 'rgba(46, 164, 79, 0.1)',
    supportsGPG: true,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Adheres to GitHub REST v3 public user endpoints. No private repo access attempted.'
  },
  gitlab: {
    id: 'gitlab',
    name: 'GitLab',
    category: 'Developer & Code',
    baseUrl: 'https://gitlab.com/',
    iconName: 'Gitlab',
    color: '#fc6d26',
    bgLight: 'rgba(252, 109, 38, 0.1)',
    supportsGPG: true,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public user profile metadata and public project commit signatures.'
  },
  twitter_x: {
    id: 'twitter_x',
    name: 'X (Twitter)',
    category: 'Microblogging',
    baseUrl: 'https://x.com/',
    iconName: 'Twitter',
    color: '#1da1f2',
    bgLight: 'rgba(29, 161, 242, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Surface-level public timeline, bios, and public media hashes. Zero authentication credential stuffing.'
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'Professional',
    baseUrl: 'https://linkedin.com/in/',
    iconName: 'Linkedin',
    color: '#0a66c2',
    bgLight: 'rgba(10, 102, 194, 0.1)',
    supportsGPG: false,
    publicApiAvailable: false,
    ethicalGuidelineNote: 'Public vanity URL matching & search index metadata. No direct private profile probing.'
  },
  reddit: {
    id: 'reddit',
    name: 'Reddit',
    category: 'Community & Forums',
    baseUrl: 'https://reddit.com/user/',
    iconName: 'MessageSquare',
    color: '#ff4500',
    bgLight: 'rgba(255, 69, 0, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public post history, subreddit submission activity, and moderation flair.'
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram (t.me)',
    category: 'Messaging & Identity',
    baseUrl: 'https://t.me/',
    iconName: 'Send',
    color: '#229ed9',
    bgLight: 'rgba(34, 158, 217, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public channel/username resolve headers (t.me/<handle> web preview) only.'
  },
  keybase: {
    id: 'keybase',
    name: 'Keybase',
    category: 'Messaging & Identity',
    baseUrl: 'https://keybase.io/',
    iconName: 'Key',
    color: '#ff6f21',
    bgLight: 'rgba(255, 111, 33, 0.1)',
    supportsGPG: true,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Cryptographic proof tree lookup (Keybase public identity API). Highly authoritative for PGP linking.'
  },
  mastodon: {
    id: 'mastodon',
    name: 'Mastodon / Fediverse',
    category: 'Microblogging',
    baseUrl: 'https://mastodon.social/@',
    iconName: 'Radio',
    color: '#6364ff',
    bgLight: 'rgba(99, 100, 255, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Decentralized ActivityPub actor endpoints and public timeline analysis.'
  },
  hackernews: {
    id: 'hackernews',
    name: 'HackerNews',
    category: 'Community & Forums',
    baseUrl: 'https://news.ycombinator.com/user?id=',
    iconName: 'Terminal',
    color: '#ff6600',
    bgLight: 'rgba(255, 102, 0, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Firebase HackerNews public item & user endpoints.'
  },
  bluesky: {
    id: 'bluesky',
    name: 'Bluesky (AT Protocol)',
    category: 'Microblogging',
    baseUrl: 'https://bsky.app/profile/',
    iconName: 'Cloud',
    color: '#0285ff',
    bgLight: 'rgba(2, 133, 255, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public ATProto repository record reading (com.atproto.repo.getRecord).'
  },
  discord_matrix: {
    id: 'discord_matrix',
    name: 'Matrix / Discord Hubs',
    category: 'Messaging & Identity',
    baseUrl: 'https://matrix.to/#/@',
    iconName: 'Hash',
    color: '#5865f2',
    bgLight: 'rgba(88, 101, 242, 0.1)',
    supportsGPG: false,
    publicApiAvailable: false,
    ethicalGuidelineNote: 'Public server directory handle references and Matrix room presence.'
  },
  medium: {
    id: 'medium',
    name: 'Medium',
    category: 'Publishing & Media',
    baseUrl: 'https://medium.com/@',
    iconName: 'BookOpen',
    color: '#00ab6c',
    bgLight: 'rgba(0, 171, 108, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public article publications, claps, and author bio metadata.'
  },
  devto: {
    id: 'devto',
    name: 'DEV Community',
    category: 'Developer & Code',
    baseUrl: 'https://dev.to/',
    iconName: 'Code',
    color: '#0a0a0a',
    bgLight: 'rgba(255, 255, 255, 0.05)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Forem public API articles, badges, and organization affiliations.'
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    category: 'Publishing & Media',
    baseUrl: 'https://youtube.com/@',
    iconName: 'PlaySquare',
    color: '#ff0000',
    bgLight: 'rgba(255, 0, 0, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public channel about section, joined date, public playlists, and community posts.'
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    category: 'Community & Forums',
    baseUrl: 'https://facebook.com/',
    iconName: 'Facebook',
    color: '#1877f2',
    bgLight: 'rgba(24, 119, 242, 0.1)',
    supportsGPG: false,
    publicApiAvailable: false,
    ethicalGuidelineNote: 'Public profile pages and search index metadata. No direct private profile probing.'
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    category: 'Publishing & Media',
    baseUrl: 'https://instagram.com/',
    iconName: 'Instagram',
    color: '#e4405f',
    bgLight: 'rgba(228, 64, 95, 0.1)',
    supportsGPG: false,
    publicApiAvailable: false,
    ethicalGuidelineNote: 'Public posts and bio metadata. No private account access attempted.'
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    category: 'Publishing & Media',
    baseUrl: 'https://tiktok.com/@',
    iconName: 'Music',
    color: '#00f2fe',
    bgLight: 'rgba(0, 242, 254, 0.1)',
    supportsGPG: false,
    publicApiAvailable: true,
    ethicalGuidelineNote: 'Public short-form video metadata and bio indexing.'
  },
  custom: {
    id: 'custom',
    name: 'Custom Surface Web Target',
    category: 'Community & Forums',
    baseUrl: 'https://',
    iconName: 'Globe',
    color: '#9333ea',
    bgLight: 'rgba(147, 51, 234, 0.1)',
    supportsGPG: false,
    publicApiAvailable: false,
    ethicalGuidelineNote: 'Permissive robot-allowed surface web indexing.'
  }
};
